processos/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/$', views.list_event, name='list_event'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/new/(?P<id_cliente>\d+)/$', views.event, name='event_new'),
]

processos/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('processos.core.urls')),
    path('processos/', include('processos.descricao.urls')),
    path('comentario/', include('processos.comment.urls')),
     path('calendario/', include('processos.cal.urls')),
]

processos/cal/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from processos.descricao.models import Description
import datetime


class Event(models.Model):
    id_comment = models.ForeignKey(Description, on_delete=models.CASCADE, verbose_name='Cliente')
    title = models.CharField('Título', max_length=200)
    description = models.TextField('Descrição')
    start_time = models.DateTimeField('Horário Inicial')
    end_time = models.DateTimeField('Horário Final')

    @property
    def get_html_url(self):
        # url link na pagina calendar/
        href = '#ID' + str(self.id)
        return f'<a data-toggle="modal" href="{href}" id="link"> {self.title} </a>'

    def format_date(self):
        diferenca = datetime.timedelta(hours=-3)
        fuso_horario = datetime.timezone(diferenca)
        tempo = self.start_time
        tempo_fuso = tempo.astimezone(fuso_horario)

        tempo_start = tempo_fuso.strftime("%d de %b  %H:%M")
        return tempo_start

    def format_date_end(self):
        diferenca = datetime.timedelta(hours=-3)
        fuso_horario = datetime.timezone(diferenca)
        tempo = self.end_time
        tempo_fuso = tempo.astimezone(fuso_horario)

        tempo_start = tempo_fuso.strftime("%d de %b  %H:%M")
        return tempo_start

    def prazo_encerrado(self):
        data_now = datetime.datetime.now()
        day_event = self.start_time.day
        month_event = self.start_time.month

        if 0 <= self.start_time.hour <= 2:
            day_event = day_event - 1

        if (day_event >= data_now.day) and (month_event >= data_now.month):
            return True
        else:
            return False


    def prazo_hoje(self):
        data_now = datetime.datetime.now()
        day_now = self.start_time.day

        if 0 <= self.start_time.hour <= 2:
            day_now = day_now - 1

        month_event = self.start_time.month

        if (day_now == data_now.day) and (month_event == data_now.month):
            return True
        else:
            return False

    def prazo_amanha(self):
        data_now = datetime.datetime.now()
        day_now = self.start_time.day

        if 0 <= self.start_time.hour <= 2:
            day_now = day_now - 1

        month_event = self.start_time.month
        amanha = int(data_now.day + 1)

        if (day_now == amanha) and (month_event == data_now.month):
            return True
        else:
            return False

processos/cal/forms.py
from django.forms import ModelForm, DateInput
from processos.cal.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

processos/cal/views.py
from datetime import timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
import calendar

from processos.cal.models import *
from processos.cal.utils import Calendar
from processos.cal.forms import EventForm
from processos.descricao.models import Description


def index(request):
    return HttpResponse('hello')


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['id_event'] = Event.objects.all()
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return date.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None, id_cliente=None):
    instance = Event()
    # Vai para link
    if event_id:
        # Link com id = event_id
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)

    if request.POST and form.is_valid():
        form.save()
        mensagem = Event.objects.last()
        return HttpResponseRedirect(reverse('cal:calendar'))

    id = Description.objects.get(id=id_cliente)

    context = {'form': form, 'id_cliente': id}

    return render(request, 'cal/event.html', context)


def list_event(request):
    template_name = 'cal/list_event.html'
    obj = Description.objects.all()

    """
    now = datetime.now()
    day_now = now.day
    month = now.strftime("%b")
    list_date = [day_now, month]
    """

    list = Event.objects.all()

    context = {'lista_event': list, 'description': obj}

    return render(request, template_name, context)

processos/cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
    integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Agenda</title>

  <style>
    body {
      margin-top: 80px
    }

    #link {
      color: white;
    }

    .card {
      margin-left: -8px;
      margin-right: 10px;
      background-color: #4444ff;
      border-bottom: 1px solid #e9ecff;
    }

    .btn {
      outline: none;
      color: black;
      background-color: transparent;
      box-shadow: 0 0 0 0;
      margin-right: 3px;
    }

    .clearfix {
      margin: 15px;
    }

    .date {
      display: block;
      color: #010101;
      text-align: right;
      margin-top: 5px;
    }

    .date-now {
      display: block;
      font-size: 18px;
      color: red;
      text-align: right;
      margin-top: 5px;
    }

    .back-table-now .card {
      margin-left: -8px;
      margin-right: 10px;
      background-color: #ff2b2b;
      border-bottom: 1px solid #e9ecff;
    }

    .back-table {
      background-color: #fafafa;
    }

    .back-table-now {
      background-color: #e0e0e0;
    }

    .month {
      background-color: #d0d0d0;
      text-transform: capitalize;
      color: black;
    }

    .calendar tr {
      background-color: #f0f0f0;
    }

    .none-week {
      background-color: #ffffff;
    }
  </style>

</head>

<body>
  {% include "includes/nav.html" %}
  <h1 style="border-bottom: 2px solid #b2b4b7;padding-bottom: 10px;" class="title">{% block title %}{% endblock %}</h1>


  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>

</html>

processos/cal/templates/cal/calendar.html
<!doctype html>
<html lang="pt-br">

<head>
    {% extends 'cal/base.html' %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <style>


    </style>


</head>

<body>
    {% block title %}
    Calendário
    {% endblock %}

    {% block content %}
    <div class="container">

        <div id="margin" class="clearfix">
            <a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> &nbsp;Próximo Mês &nbsp;<i
                    class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            <a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ prev_month }}"><i
                    class="fa fa-arrow-circle-left" aria-hidden="true"></i> &nbsp;Mês Anterior &nbsp; </a>
            <!--<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> Adicionar Evento </a>-->
        </div>

        {{ calendar }}
        {% for event in id_event %}
        <div class="modal fade" id="ID{{event.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel" style="text-transform: capitalize;">
                            {{ event.title }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">

                        {{ event.description }}
                    </div>

                    <div class="modal-footer">
                        <p style="padding-right: 0px; margin-bottom: -3px;">{{ event.format_date }} —
                            {{ event.format_date_end }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}


    </div>
    {% endblock %}

</body>

</html>

processos/cal/templates/cal/event.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <title>Eventos</title>
    <style>
        #titulo_form {
            border-bottom: 2px solid #b2b4b7;
            padding-bottom: 10px;
            margin-top: -30px;
        }

        .jumbotron {
            width: 70%;
            margin: auto;
        }

        .button-form {
            margin-top: 10px;
            text-align: right;
        }
    </style>
</head>

<body>
    {% extends 'base.html' %}
    {% block content %}
    <div class="jumbotron">
        <div class="container">
            <h2 id="titulo_form" style="margin-bottom: 30px;" class="text-center">Criar Evento</h2>

            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}

            <form method="POST" novalidate="">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-12">

                        <div class="form-group">
                            <input type="hidden" name="id_comment" id="id_id_comment" value="{{ id_cliente.id }}">
                        </div>

                        <div class="form-group">
                            <label for="id_title">
                                Título
                            </label>
                            <input type="text" name="title" maxlength="200" required="" class="form-control"
                                id="id_title">
                        </div>

                        <div class="form-group">
                            <label for="id_description">
                                Descrição
                            </label>
                            <textarea name="description" cols="40" rows="10" required="" class="form-control"
                                id="id_description"></textarea>
                        </div>

                        <div class="form-row">

                            <div style="margin-top: 10px;" class="col-md-6 mb-3">
                                <label for="id_start_time">
                                    Horário Inicial
                                </label>
                                <input type="datetime-local" name="start_time" required="" class="form-control"
                                    id="id_start_time">
                            </div>

                            <div style="margin-top: 10px;" class="col-md-6 mb-3">
                                <label for="id_start_time">
                                    Horário Final
                                </label>
                                <input type="datetime-local" name="end_time" required="" class="form-control"
                                    id="id_end_time">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="button-form">
                    <a href="{% url 'cal:calendar' %}">
                        <button style="margin-right: 10px;" type="button" class="btn btn-info">
                            <span class="fa fa-calendar"></span>&nbsp;&nbsp;Calendário
                        </button>
                    </a>
                    <button type="submit" class="btn btn-success">
                        <span class="fa fa-check"></span>Salvar
                    </button>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}
</body>

</html>

processos/cal/templates/cal/list_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todos os eventos</title>

    <style>
        .mb-1   {
            max-width: 80ch;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            text-transform: capitalize;
        }
        .jumbotron {
            width: 85%;
            margin: auto;
        }
        #titulo_form {
            border-bottom: 2px solid #b2b4b7;
            padding-bottom: 10px;
        }
        #link {
            color: #000000;
        }
        #link: hover {
            color: #bbbbbb;
        }
    </style>
</head>
<body>
{% extends "base.html" %}
{% block content %}

<div class="geral">
    <div class="jumbotron">
    <!-- Pegar cada evento apenas -->
        <div style="margin-top: -30px;" class="container">
            <h2 id="titulo_form" style="margin-bottom: 30px;" class="text-center">Eventos definidos</h2>

            {% for obj in description %}
            <div style="margin-top:10px;" id="accordion">
                <div class="card">
                    <div class="card-header" id="ID{{ obj.id }}">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#ID{{ obj.id }}{{ obj.id }}" aria-expanded="false" aria-controls="ID{{ obj.id }}{{ obj.id }}">
                                <strong id="link" style="text-transform: capitalize;">{{ obj.cliente }}</strong>
                            </button>
                        </h5>
                    </div>

                    <div id="ID{{ obj.id }}{{ obj.id }}" class="collapse" aria-labelledby="ID{{ obj.id }}" data-parent="#accordion">
                        <div class="card-body">
                            {%for event in lista_event %}
                            {% if obj.id == event.id_comment.id %}

                            {% if event.prazo_encerrado %}
                            <div class="list-group">
                                <a data-toggle="modal" href="#PK{{ event.id }}" class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ event.title }}</h5>
                                        <small class="text-muted">{{ event.format_date }}</small>
                                    </div>
                                    <p class="mb-1">{{ event.description }}</p>
                                </a>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="PK{{ event.id }}" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="ModalLabel" style="text-transform: capitalize;">{{ event.title }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>

                                        <div class="modal-body">
                                            {{ event.description }}
                                        </div>

                                        <div class="modal-footer">
                                            <p style="padding-right: 0px;">{{ event.start_time }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            {% endif %}
                            {% endif %}
                            {% endfor %}

                            <div style="margin-top: 15px; margin-bottom: -5px;" class="alert alert-dark" role="alert">
                                <strong style="text-align: center;">Eventos encerrados.</strong>
                            </div>

                            {%for event in lista_event %}
                            {% if obj.id == event.id_comment.id %}

                            {% if event.prazo_encerrado != True %}
                            <div class="list-group">
                                <a data-toggle="modal" href="#ID{{ event.id }}" style="background-color: #E9ECEF;" class="list-group-item list-group-item-action flex-column align-items-start">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ event.title }}</h5>
                                        <small class="text-muted">{{ event.format_date }}</small>
                                    </div>
                                    <p class="mb-1">{{ event.description }}</p>
                                </a>
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" id="ID{{ event.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModal" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModal" style="text-transform: capitalize;">{{ event.title }}</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>

                                        <div class="modal-body">
                                            {{ event.description }}
                                        </div>

                                        <div class="modal-footer">
                                            <p style="padding-right: 0px;">{{ event.start_time }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock content %}

</body>
</html>