processos/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/$', views.list_event, name='list_event'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/new/(?P<id_cliente>\d+)/$', views.event, name='event_new'),
]

processos/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'


urlpatterns = [
    path('<int:pk>/', views.processo_comment_detail, name='processo_comment_detail'),
    path('<int:pk>/deletar', views.comment_delete, name='comment_delete'),
    path('<int:pk>/editar', views.comment_update, name='comment_update'),
    path('<int:pk>/event', views.comment_event, name='comment_event'),
    path('<int:pk>/add/', views.processo_comment_form, name='processo_comment_form'),
]

processos/descricao/urls.py
from django.urls import path
from . import views

# Nome do aplicativo
app_name = 'description'

# Urls, 'nome', views.definição_do_Que_vai_ser_visto, name='nome_para_chamar_url'
urlpatterns = [
    path('', views.processo_list, name='processo_list'),
    path('<int:pk>/', views.processo_detail, name='processo_detail'),
    path('add/', views.ProcessoCreate.as_view(), name='processo_add'),
    path('deletar/<int:id>/', views.processo_delete, name='processo_delete'),
]

processos/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('processos.core.urls')),
    path('processos/', include('processos.descricao.urls')),
    path('comentario/', include('processos.comment.urls')),
     path('calendario/', include('processos.cal.urls')),
]

processos/comment/models.py
from django.db import models
from django.urls import reverse_lazy
from processos.descricao.models import Description
from processos.core.models import TimeStampedModel


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Comments(TimeStampedModel):
    n_processo = models.ForeignKey(Description, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200, blank=True, null=True)
    comment = models.TextField('Observações', blank=True, null=True)

    class Meta:
        """Ordering é uma tupla que contém os índices dos campos. """
        ordering = ('-created',)

    def __str__(self):
        # Returna id_comments - id_description - cliente - natureza
        return '{} : Proc-{}'.format(self.n_processo.id, self.n_processo.pasta)

    def get_absolute_url(self):
        return reverse_lazy('comment:comment_detail', kwargs={'pk': self.pk})

    def cliente_formatado(self):
        nome = self.n_processo.cliente

        return str(nome.title())

processos/comment/forms.py
from django import forms
from .models import Comments



"""
class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

"""
class CommentsForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = '__all__' # todos os campos

processos/comment/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Comments
from processos.descricao.models import Description
from django.contrib.auth.decorators import login_required

from .forms import CommentsForm
from django.views.generic import CreateView, UpdateView

from processos.cal.models import Event


@login_required(login_url='core:logar_user')
def processo_comment_detail(request, pk):
    template_name = 'processo_comment_detail.html'
    descrip = Description.objects.get(id=pk)
    obj = Comments.objects.filter(n_processo=pk)
    # event = Event.objects.filter(id_comment=pk)

    # context = {'obj_list_detail': obj, 'cliente_detail': descrip, 'event': event}
    context = {'obj_list_detail': obj, 'cliente_detail': descrip}

    return render(request, template_name, context)


def comment_delete(request, pk):
    comentario = Comments.objects.get(pk=pk)
    id = comentario.n_processo.id
    comentario.delete()
    return redirect('comment:processo_comment_detail', pk=id)


def comment_update(request, pk):
    template_name = 'processo_comment_edit.html'
    comentario = get_object_or_404(Comments, pk=pk)
    id = comentario.n_processo.id
    description = Description.objects.get(id=id)
    form = CommentsForm(instance=comentario)

    if request.method == 'POST':
        form = CommentsForm(request.POST, instance=comentario)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.n_processo = form.cleaned_data['n_processo']
            comentario.titulo = form.cleaned_data['titulo']
            comentario.comment = form.cleaned_data['comment']

            comentario.save()
            return redirect('comment:processo_comment_detail', pk=id)
        else:
            return render(request, template_name, {'comentario': comentario, 'form': form})

    elif request.method == 'GET':
        return render(request, template_name, {'comentario': comentario, 'form': form})


def comment_event(request, pk):
    template_name = 'comment_event.html'
    obj = Event.objects.filter(id_comment=pk)

    context = {'comment_event': obj, 'id': pk}  # Dict que possui as descrições dos objetos da classe produto

    return render(request, template_name, context)


def processo_comment_form(request, pk):
    template_name = 'processo_comment_form.html'
    description = Description.objects.get(id=pk)

    if request.method == "POST":
        form = CommentsForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('comment:processo_comment_detail', pk=pk)

    else:
        form = CommentsForm()

    context = {'cliente_detail': description, 'form': form}

    return render(request, template_name, context)

processos/comment/templates/comment_event.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Eventos</title>

    <style>
        .jumbotron {
            width: 75%;
            margin: auto;
        }

        #titulo_form {
            border-bottom: 2px solid #b2b4b7;
            padding-bottom: 10px;
        }

        #link_seta {
            color: rgb(52, 58, 64);
        }

        #link_seta :hover {
            color: rgba(52, 58, 64, 0.7);
        }

        #link {
            color: #000000;
        }

        #link:hover {
            color: #bbbbbb;
        }

        .geral {
            margin-top: -30px;
        }
    </style>

</head>

<body>
    {% extends "base.html" %}

    {% block content %}
    <a id="link_seta" href="{% url 'comment:processo_comment_detail'  id %}">
        <i class="fa fa-chevron-circle-left fa-2x" aria-hidden="true"></i>
    </a>
    <div class="geral">
        <div class="jumbotron">
            <div style="margin-top: -30px;" class="container">

                <h2 id="titulo_form" style="margin-bottom: 30px;" class="text-center">Eventos definidos</h2>
                {% if comment_event %}
                {% for obj in comment_event %}


                <div style="margin-top:10px;" id="accordion">
                    <div class="card">
                        <div class="card-header" id="ID{{ obj.id }}">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse"
                                    data-target="#ID{{ obj.id }}{{ obj.id }}" aria-expanded="false"
                                    aria-controls="ID{{ obj.id }}{{ obj.id }}">
                                    <strong id="link" style="text-transform: capitalize;">{{ obj.title }}</strong>
                                </button>
                            </h5>
                        </div>
                        <div id="ID{{ obj.id }}{{ obj.id }}" class="collapse" aria-labelledby="ID{{ obj.id }}"
                            data-parent="#accordion">
                            <div class="card-body">
                                &nbsp;&nbsp;&nbsp;{{ obj.description }}
                            </div>

                            <div style="margin: -5px;" class="modal-footer">
                                <p style="font-size:14px;" class="text-muted">Data do evento: &nbsp; {{ obj.start_time
                                    }} — {{ obj.end_time }}</p>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}

                {% else %}
                <p style="margin-top: 30px; text-align: center;" class="alert alert-warning">Sem Eventos na agenda.</p>
                {% endif %}
            </div>
            </divv>
        </div>
        {% endblock content %}
</body>

</html>

processos/comment/templates/processo_comment_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalhes</title>

    <style>
        #link_seta {
            color: rgb(52, 58, 64);
        }
        #link_seta :hover {
            color:  rgba(52, 58, 64, 0.7);
        }
        #title_name {
            text-align: center;
            font-size: 35px;
        }
        .table_info {
            text-align: right;
        }
        .mb-1   {
            max-width: 80ch;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
        .geral {
            margin-top: -30px;
        }
    </style>

</head>
<body>
{% extends "base.html" %}
{% block content %}

    <!-- link para voltar na pagína anterior  url 'app:urls' -->
        <a id="link_seta" href="{% url 'description:processo_detail' cliente_detail.pk %}">
            <i class="fa fa-chevron-circle-left fa-2x" aria-hidden="true"></i>
        </a>
<div class="geral">

    <div class="button_comment">

    <h1>
    <span class="pull-right">
            <a href="{% url 'comment:processo_comment_form' cliente_detail.pk %}">
            <button style="margin-left: 15px;" type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span>&nbsp;Adicionar
            </button>
        </a>
    </span>

    </h1>
    <h1>
        <span class="pull-right">
            <a href="{% url 'description:processo_detail' cliente_detail.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="fa fa-folder"></span>
                    Detalhes
                </button> <!-- botão para editar o produto-->
            </a>
        </span>
    </h1>

    <h1>
        <span style="margin-right:15px;" class="pull-right">
            <div class="btn-group">
                <button type="button" class="btn btn-danger"> <span class="fa fa-calendar"></span>&nbsp;&nbsp;Evento</button>
                <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'cal:event_new' cliente_detail.pk %}">Criar novo evento</a>
                    <a class="dropdown-item" href="{% url 'comment:comment_event' cliente_detail.pk %}">Lista de eventos</a>
                </div>
            </div>
        </span>
    </h1>
    </div>

        <div class="col-sm-6">
            <h1 class="text-center">{{ cliente_detail.cliente_formatado }}</h1>
            <table class="table table-user-information">
                <tbody>
                    <tr>
                        <th class="table_info">Proc-</th>
                        <td>{{ cliente_detail.pasta_formatado }}</td>
                    </tr>
                    <tr>
                        <th class="table_info">Natureza</th>
                        <td style="text-transform: capitalize;">{{ cliente_detail.natureza}}</td>
                    </tr>
                    <tr>
                        <th class="table_info">Tipo de Ação</th>
                        <td style="text-transform: capitalize;">{{ cliente_detail.tipo_action }}</td>
                    </tr>

                </tbody>
            </table>
        </div>


        <table style="margin-top: 50px;  margin-bottom: -10px;" class="table table-striped">
            <thead>
                <tr>
                    <th class="text-center" width="100%"><h4>Observações</h4></th>
                </tr>
            </thead>
        </table>

    {% if obj_list_detail %}
        <div style="margin-bottom: 40px;" class="card-body">
            {% for obj in obj_list_detail %}
                        <div class="list-group">
                            <a data-toggle="modal" href="#ID{{ obj.id }}" style="background-color: #E9ECEF;" class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 style="text-transform: capitalize;" class="mb-1">{{ obj.titulo }}</h5>
                                    <small class="text-muted">{{ obj.created }}</small>
                                </div>
                                <p class="mb-1">{{ obj.comment }}</p>
                            </a>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="ID{{ obj.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModal" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 style="text-transform: capitalize;" class="modal-title" id="exampleModal">{{ obj.titulo }}</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                        <div class="modal-body">
                                            {{ obj.comment }}
                                        </div>
                                        <div class="modal-footer">
                                           <a href="{% url 'comment:comment_delete' obj.pk %}">
                                               <button type="button" class="btn btn-danger">
                                                    <span class="fa fa-times"></span>
                                                    Apagar
                                                </button>
                                            </a>
                                            <a href="{% url 'comment:comment_update' obj.pk %}">
                                               <button type="button" class="btn btn-success">
                                                    <span class="fa fa-pencil-square-o" aria-hidden="true"></span>
                                                     Editar
                                                </button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                {% endfor %}
                    </div>
    {% else %}
        <!-- COLOCAR NO CARD -->
        <p style="margin-top: 30px; text-align: center;" class="alert alert-warning">Sem itens na lista.</p>
    {% endif %}
</div>

{% endblock content %}
</body>
</html>

processos/comment/templates/processo_comment_edit.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <!-- Titulo -->
    <title>Editar Observações</title>

    <!-- Configurações do css margens, bordas e asterístico -->
    <style>
        .jumbotron {
            width: 75%;
            margin: auto;
        }
        #titulo_form {
            border-bottom: 2px solid #b2b4b7;
            padding-bottom: 10px;
        }
        .button_form {
            margin-top: 20px;
            text-align: right;
        }
    </style>
</head>
<body>
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

<div class="jumbotron">
    <div class="container">
        <!-- Criando um formulario com método POST -->
        <form method="POST" novalidate="">
            <!-- Token para liberar postar no formulario (Segurança) -->
            {% csrf_token %}
            <!-- Titulo -->
            <h2 id="titulo_form" style="margin-bottom: 30px;" class="text-center">{{ comentario.cliente_formatado }}</h2>

            <!-- Classe: Para cada caixa ficar um embaixo do outro-->
            <div class="row">
                <!-- Classe: tamanho da caixa -->
                <div class="col-sm-12">
                    <div class="form-group" >
                        <!-- Não é visível(hidden) para o usário este campo -->
                        <input type="hidden" name="n_processo" id="id_n_processo" value="{{ comentario.n_processo_id }}">
                    </div>
                    <div class="form-group">
                        <label for="id_titulo">
                            Título
                        </label>
                        <input type="text" name="titulo" value="{{ comentario.titulo }}" maxlength="200" class="form-control" id="id_titulo">
                    </div>
                    <div class="form-group">
                        <label for="id_comment">
                            Observações
                        </label>
                        <textarea name="comment" cols="40" rows="10" class="form-control" id="id_comment">{{ comentario.comment }}</textarea>
                    </div>
                </div>
            </div>

            <!-- Classe: grupo de botões (Criado por mim)-->
            <div class="button_form">
                <a href="{% url 'comment:processo_comment_detail' comentario.n_processo_id %}">
                <button style="margin-right: 10px;" type="submit" class="btn btn-success">
                    <span class="fa fa-check"></span>&nbsp;Salvar
                </button>
                </a>

                <!-- Redireciona para a url caso for clicado -->
                <a href="{% url 'comment:processo_comment_detail' comentario.n_processo_id %}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-close"></span>&nbsp;Cancelar
                    </button>
                </a>
            </div>

        </form>
    </div>
</div>


{% endblock content %}
</body>
</html>

processos/comment/templates/processo_comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Titulo -->
    <title>Observações</title>

    <!-- Configurações do css margens, bordas e asterístico -->
    <style>
        .jumbotron {
            width: 75%;
            margin: auto;
        }
        #titulo_form {
            border-bottom: 2px solid #b2b4b7;
            padding-bottom: 10px;
        }
        .button_form {
            margin-top: 20px;
            text-align: right;
        }
    </style>
</head>

<body>
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

<!-- Criando uma caixa com padrão 1000px de largura -->
<div class="jumbotron">
    <div style="margin-top: -30px;" class="container">
        <!-- Criando um formulario com método POST -->
        <form method="POST" novalidate="">
            <!-- Token para liberar postar no formulario (Segurança) -->
            {% csrf_token %}
            <!-- Titulo -->
            <h2 id="titulo_form" style="margin-bottom: 30px;" class="text-center">{{ cliente_detail.cliente_formatado }}</h2>

            <!-- Classe: Para cada caixa ficar um embaixo do outro-->
            <div class="row">
                <!-- Classe: tamanho da caixa -->
                <div class="col-sm-12">
                    <div class="form-group" >
                        <!-- Não é visível(hidden) para o usário este campo -->
                        <input type="hidden" name="n_processo" id="id_n_processo" value="{{ cliente_detail.id }}">
                    </div>
                    <div class="form-group">
                        <label for="id_titulo">
                            Título
                        </label>
                        <input type="text" name="titulo" maxlength="200" class="form-control" id="id_titulo">
                    </div>
                    <div class="form-group">
                        <label for="id_comment">
                            Observações
                        </label>
                        <textarea name="comment" cols="40" rows="10" class="form-control" id="id_comment"></textarea>
                    </div>
                </div>
            </div>

            <!-- Classe: grupo de botões (Criado por mim)-->
            <div class="button_form">
                <button style="margin-right: 10px;" type="submit" class="btn btn-success">
                    <span class="fa fa-check"></span>&nbsp;Salvar
                </button>

                <!-- Redireciona para a url caso for clicado -->
                <a href="{% url 'comment:processo_comment_detail' cliente_detail.pk %}  ">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-close"></span>&nbsp;Cancelar
                    </button>
                </a>
            </div>

        </form>
    </div>
</div>

{% endblock content %}
</body>
</html>