processos/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/$', views.list_event, name='list_event'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/new/(?P<id_cliente>\d+)/$', views.event, name='event_new'),
]

processos/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'


urlpatterns = [
    path('<int:pk>/', views.processo_comment_detail, name='processo_comment_detail'),
    path('<int:pk>/deletar', views.comment_delete, name='comment_delete'),
    path('<int:pk>/editar', views.comment_update, name='comment_update'),
    path('<int:pk>/event', views.comment_event, name='comment_event'),
    path('<int:pk>/add/', views.processo_comment_form, name='processo_comment_form'),
]

processos/core/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'core'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('cadastrar_usuario/',views.cadastrar_user, name="cadastrar_user"),
    path('deslogar_usuario/', views.deslogar_user, name="deslogar_user"),
    path('alterar_senha/', views.alterar_senha, name="alterar_senha"),
    path('', views.logar_user, name="logar_user"),
]

processos/descricao/urls.py
from django.urls import path
from . import views

# Nome do aplicativo
app_name = 'description'

# Urls, 'nome', views.definição_do_Que_vai_ser_visto, name='nome_para_chamar_url'
urlpatterns = [
    path('', views.processo_list, name='processo_list'),
    path('<int:pk>/', views.processo_detail, name='processo_detail'),
    path('add/', views.ProcessoCreate.as_view(), name='processo_add'),
    path('deletar/<int:id>/', views.processo_delete, name='processo_delete'),
]

processos/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('processos.core.urls')),
    path('processos/', include('processos.descricao.urls')),
    path('comentario/', include('processos.comment.urls')),
     path('calendario/', include('processos.cal.urls')),
]

processos/comment/models.py
from django.db import models
from django.urls import reverse_lazy
from processos.descricao.models import Description
from processos.core.models import TimeStampedModel


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Comments(TimeStampedModel):
    n_processo = models.ForeignKey(Description, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200, blank=True, null=True)
    comment = models.TextField('Observações', blank=True, null=True)

    class Meta:
        """Ordering é uma tupla que contém os índices dos campos. """
        ordering = ('-created',)

    def __str__(self):
        # Returna id_comments - id_description - cliente - natureza
        return '{} : Proc-{}'.format(self.n_processo.id, self.n_processo.pasta)

    def get_absolute_url(self):
        return reverse_lazy('comment:comment_detail', kwargs={'pk': self.pk})

    def cliente_formatado(self):
        nome = self.n_processo.cliente

        return str(nome.title())

processos/core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    """Cria uma tabela que contém as informações de criação do produto e sua modificação"""
    created = models.DateTimeField('criado em', auto_now=False, auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True

processos/descricao/models.py
from django.db import models
from django.urls import reverse_lazy


class Description(models.Model):
    """Cria uma tabela com as descrições do processo."""
    pasta = models.PositiveIntegerField('Proc- ', unique=True)
    escritorio_responsavel = models.CharField('Escritório responsável', max_length=15, default='NPJ-UNIVAG')
    escritorio_origem = models.CharField('Escritório de Origem', max_length=15, default='NPJ-UNIVAG', null=True, blank=True)
    codigo_processo = models.CharField('Código do processo', max_length=10, default='PJE', null=True, blank=True)
    cliente = models.CharField('Cliente no NPJ-UNIVAG', max_length=100)
    contrario = models.CharField('Contrário', max_length=100)
    tipo_action = models.CharField('Tipo de ação', max_length=100)
    n_principal = models.PositiveIntegerField('Nº Principal', null=True, blank=True)
    orgao_principal = models.CharField('Orgão', max_length=128, null=True, blank=True)
    professor = models.CharField('Professor Orientador', max_length=100, default='BRUNO HENRIQUE DA ROCHA', null=True, blank=True)
    natureza = models.CharField('Natureza', max_length=100)
    status = models.BooleanField('Encerrado', default=False)


    class Meta:
        ordering = ('cliente',)

    def __str__(self):
        # Esta função permite que a saída seja legível para o humano, ou seja, o que vai ser requirido no Description.objects.all()
        return self.cliente

    # Para ir ao url quando chamar a função com o id.
    def get_absolute_url(self):
        return reverse_lazy('description:processo_detail', kwargs={'pk': self.pk})

    # Retorna uma saída com o dado Cliente Formatado de forma elegante.
    def cliente_formatado(self):
        nome = self.cliente
        return str(nome.title())

    # Retorna uma saída com o dado do n_principal de forma organizada.
    def n_principal_formatado(self):
        if len(str(self.n_principal)) >= 16:
            numero = str(self.n_principal)
            numero = numero.strip()
            parte_1 = numero[:7]
            parte_2 = numero[7:9]
            parte_3 = numero[9:13]
            parte_4 = numero[13]
            parte_5 = numero[14:16]
            parte_6 = numero[16:]
            numero_formatado = parte_1 + '-' + parte_2 + '.' + parte_3 + '.' + parte_4 + '.' + parte_5 + '.' + parte_6
        else:
            numero_formatado = False
        return numero_formatado

    # Retorna o dado pasta formatado de forma elegante.
    def pasta_formatado(self):
        # zfill(number_max_digitos), com zero preenchido a esquerda.
        return str(self.pasta).zfill(7)

processos/cal/forms.py
from django.forms import ModelForm, DateInput
from processos.cal.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

processos/comment/forms.py
from django import forms
from .models import Comments



"""
class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

"""
class CommentsForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = '__all__' # todos os campos

processos/descricao/forms.py
from django import forms
from .models import Description

# Criação de uma formulário
class DescriptionForm(forms.ModelForm):

    class Meta:
        model = Description
        # Pega todos os campos da tabela Description.
        fields = '__all__'

processos/cal/views.py
from datetime import timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
import calendar

from processos.cal.models import *
from processos.cal.utils import Calendar
from processos.cal.forms import EventForm
from processos.descricao.models import Description


def index(request):
    return HttpResponse('hello')


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['id_event'] = Event.objects.all()
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return date.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None, id_cliente=None):
    instance = Event()
    # Vai para link
    if event_id:
        # Link com id = event_id
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)

    if request.POST and form.is_valid():
        form.save()
        mensagem = Event.objects.last()
        return HttpResponseRedirect(reverse('cal:calendar'))

    id = Description.objects.get(id=id_cliente)

    context = {'form': form, 'id_cliente': id}

    return render(request, 'cal/event.html', context)


def list_event(request):
    template_name = 'cal/list_event.html'
    obj = Description.objects.all()

    """
    now = datetime.now()
    day_now = now.day
    month = now.strftime("%b")
    list_date = [day_now, month]
    """

    list = Event.objects.all()

    context = {'lista_event': list, 'description': obj}

    return render(request, template_name, context)

processos/comment/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Comments
from processos.descricao.models import Description
from django.contrib.auth.decorators import login_required

from .forms import CommentsForm
from django.views.generic import CreateView, UpdateView

from processos.cal.models import Event


@login_required(login_url='core:logar_user')
def processo_comment_detail(request, pk):
    template_name = 'processo_comment_detail.html'
    descrip = Description.objects.get(id=pk)
    obj = Comments.objects.filter(n_processo=pk)
    # event = Event.objects.filter(id_comment=pk)

    # context = {'obj_list_detail': obj, 'cliente_detail': descrip, 'event': event}
    context = {'obj_list_detail': obj, 'cliente_detail': descrip}

    return render(request, template_name, context)


def comment_delete(request, pk):
    comentario = Comments.objects.get(pk=pk)
    id = comentario.n_processo.id
    comentario.delete()
    return redirect('comment:processo_comment_detail', pk=id)


def comment_update(request, pk):
    template_name = 'processo_comment_edit.html'
    comentario = get_object_or_404(Comments, pk=pk)
    id = comentario.n_processo.id
    description = Description.objects.get(id=id)
    form = CommentsForm(instance=comentario)

    if request.method == 'POST':
        form = CommentsForm(request.POST, instance=comentario)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.n_processo = form.cleaned_data['n_processo']
            comentario.titulo = form.cleaned_data['titulo']
            comentario.comment = form.cleaned_data['comment']

            comentario.save()
            return redirect('comment:processo_comment_detail', pk=id)
        else:
            return render(request, template_name, {'comentario': comentario, 'form': form})

    elif request.method == 'GET':
        return render(request, template_name, {'comentario': comentario, 'form': form})


def comment_event(request, pk):
    template_name = 'comment_event.html'
    obj = Event.objects.filter(id_comment=pk)

    context = {'comment_event': obj, 'id': pk}  # Dict que possui as descrições dos objetos da classe produto

    return render(request, template_name, context)


def processo_comment_form(request, pk):
    template_name = 'processo_comment_form.html'
    description = Description.objects.get(id=pk)

    if request.method == "POST":
        form = CommentsForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('comment:processo_comment_detail', pk=pk)

    else:
        form = CommentsForm()

    context = {'cliente_detail': description, 'form': form}

    return render(request, template_name, context)

processos/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import  AuthenticationForm, UserCreationForm, PasswordChangeForm


@login_required(login_url='core:logar_user')
def index(request):
    template_name = 'index.html'
    return render(request,template_name)


def logar_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('core:index')
        else:
            form_login = AuthenticationForm()
    else:
        form_login = AuthenticationForm()
    return render(request, 'login.html', {'form_login': form_login})


def cadastrar_user(request):
    if request.method == 'POST':
        form_user = UserCreationForm(request.POST)
        if form_user.is_valid():
            form_user.save()
            return redirect('core:index')

    else:
        form_user = UserCreationForm()

    context = {'form_user': form_user}
    return render(request, 'cadastro.html', context)


@login_required(login_url='core:logar_user')
def deslogar_user(request):
    logout(request)
    return redirect('core:logar_user')


@login_required(login_url='core:logar_user')
def alterar_senha(request):
    if request.method == "POST":
        form_senha = PasswordChangeForm(request.user, request.POST)
        if form_senha.is_valid():
            user = form_senha.save()
            update_session_auth_hash(request, user)
            return redirect('core:index')
    else:
        form_senha = PasswordChangeForm(request.user)
    return render(request, 'alterar_senha.html', {'form_senha': form_senha})

processos/descricao/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import HttpResponseRedirect
from .models import Description
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Formulários
from django.views.generic import CreateView
from .forms import DescriptionForm


@login_required(login_url='core:logar_user')
# Função: exibe a página inical dos processo, ou seja, a lista.
def processo_list(request):
    # Template_name: layout da página que é escrito em .html
    template_name = 'processo_list.html'
    # Pega o objetos da tabela Description.
    objects = Description.objects.all()
    # Dicionário que possui como valor, uma lista dos campos da tabela Description
    context = {'object_list_dict': objects}

    # Retorna a requisição, pagina html e dicionario.
    return render(request, template_name, context)


# Função: exibe a pagina de detalhes do processo através do id (pk) fornecido.
def processo_detail(request, pk):
    template_name = 'processo_detail.html'
    # Pega os campos do id fornecido (pk) da tabela Description
    obj = Description.objects.get(pk=pk)

    context = {'object_detail': obj}

    return render(request, template_name, context)


# Função: apagar um objeto caso for requisitado.
def processo_delete(request, id):
    post = Description.objects.get(pk=id)
    post.delete()
    return redirect('description:processo_list')


# Página de exibição do formulário.
def produto_add(request):
    form = DescriptionForm(request.POST or None)
    template_name = 'processo_form.html'

    # Confirmar se o formulario está adequado
    if request.GET == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('description:processo_list'))

    context = {'form': form}
    return render(request, template_name, context)


# Cria um formulário que vai ser fornecido pela função produto_add
class ProcessoCreate(CreateView):
    model = Description
    template_name = 'processo_form.html'
    form_class = DescriptionForm

processos/descricao/templates/processo_detail.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <!-- Titulo -->
    <title>Detalhes</title>

    <!-- Definições para o template - CSS -->
    <style>
        .col-sm-6 {
            margin-bottom: 1px;
        }

        #link_seta {
            color: rgb(52, 58, 64);
        }

        #link_seta :hover {
            color: rgba(52, 58, 64, 0.7);
        }

        .upper {
            text-transform: uppercase;
        }

        .capitali {
            text-transform: capitalize;
        }

        .geral {
            margin-top: -30px;
            margin-bottom: 40px;
        }
    </style>
</head>

<body>
    {% extends "base.html" %}
    {% block content %}

    <!-- link para voltar na pagína anterior  url 'app:urls' -->
    <a id="link_seta" href="{% url 'description:processo_list' %}">
        <i class="fa fa-chevron-circle-left fa-2x" aria-hidden="true"></i>
    </a>

    <div class="geral">

        <!-- Cabeçalho com botões -->
        <h1 style="margin-bottom: 15px;">
            <!-- botão para apagar o produto -->
            <span class="pull-right">
                <a href="{% url 'description:processo_delete' object_detail.pk %}">
                    <button type="button" class="btn btn-danger">
                        <span class="fa fa-times"></span>
                        Apagar
                    </button>
                </a>
            </span>
            <!-- botão para editar o produto-->
            <span style="margin-right: 15px;" class="pull-right">
                <a href="{% url 'comment:processo_comment_detail' object_detail.pk %}">
                    <button type="button" class="btn btn-info">
                        <span class="fa fa-folder"></span>
                        Observações
                    </button>
                </a>
            </span>
        </h1>

        <!-- Tabela de informações do usuário-->
        <div class="col-sm-6">
            <h1 class="text-center">{{ object_detail }}</h1>
            <table class="table table-user-information">
                <!-- th: título td: informação do usário -->
                <tbody>
                    <tr>
                        <th class="text-right">Status</th>
                        <td>
                            <!-- Caso objeto for importado, faça: (mudar a cor do ícone) -->
                            {% if object_detail.status%}
                            <i class="fa fa-check-circle ok"></i>
                            {% else %}
                            <i class="fa fa-minus-circle no"></i>
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th class="text-right">Proc-</th>
                        <td>{{ object_detail.pasta_formatado }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Escritório Responsável</th>
                        <td class="upper">{{ object_detail.escritorio_responsavel }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Escritório de Origem</th>
                        <td class="upper">{{ object_detail.escritorio_origem }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Código de Processo</th>
                        <td class="upper">{{ object_detail.codigo_processo }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Cliente</th>
                        <td class="capitali">{{ object_detail.cliente }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Contrário</th>
                        <td class="capitali">{{ object_detail.contrario }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Tipo de Ação</th>
                        <td class="capitali">{{ object_detail.tipo_action }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Nº Principal</th>
                        <td>{% if object_detail.n_principal_formatado != False %}
                            {{ object_detail.n_principal_formatado }}
                            {% else %}
                            {{ object_detail.n_principal }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th class="text-right">Orgão Principal</th>
                        <td class="capitali">{{ object_detail.orgao_principal }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Professor</th>
                        <td class="upper">{{ object_detail.professor }}</td>
                    </tr>
                    <tr>
                        <th class="text-right">Natureza</th>
                        <td class="capitali">{{ object_detail.natureza }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

processos/descricao/templates/processo_form.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <!-- Titulo -->
    <title>Formulário</title>

    <!-- Configurações do css margens, bordas e asterístico -->
    <style>
        span.required:after {
            content: " *";
            color: red;
        }

        .button_form {
            margin-top: 20px;
            text-align: right;
        }

        #titulo_form {
            border-bottom: 2px solid #b2b4b7;
            padding-bottom: 10px;
        }
    </style>
</head>

<body>
    {% extends "base.html" %}
    <!-- https://github.com/jazzband/django-widget-tweaks -->
    {% load widget_tweaks %}
    {% block content %}

    <!-- Criando uma caixa com padrão 1000px de largura -->
    <div class="jumbotron">
        <div style="margin-top: -30px;" class="container">
            <!-- Criando um formulario com método POST -->
            <form class="needs-validation" method="POST" novalidate>
                <!-- Token para liberar postar no formulario (Segurança) -->
                {% csrf_token %}
                <!-- Titulo -->
                <h1 id="titulo_form" style="margin-bottom: 50px;" class="text-center">Formulário</h1>

                <!-- Classe: grupo de caixa de formulário (ficar na mesma linha) -->
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="id_pasta">
                            <span class="required">Proc- </span>
                            <!--Escolha Obrigatória -->
                        </label>
                        <input type="number" name="pasta" min="0" class="form-control" required="" id="id_pasta">
                        <!-- Enviar um feedback(reposta) caso os dados não seja inserido -->
                        <div class="invalid-feedback">
                            Por favor, forneça apenas os números.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_codigo_processo">
                            <!-- Escolha não obrigatória -->
                            Código do processo
                        </label>
                        <input type="text" name="codigo_processo" value="PJE" maxlength="10" class="form-control"
                            id="id_codigo_processo">
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="id_escritorio_responsavel">
                            <span class="required">Escritório responsável</span>
                        </label>
                        <input type="text" name="escritorio_responsavel" value="NPJ-UNIVAG" maxlength="15"
                            class="form-control" required="" id="id_escritorio_responsavel">
                        <div class="invalid-feedback">
                            Por favor, forneça o nome do escritório responsável.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_escritorio_origem">
                            Escritório de Origem
                        </label>
                        <input type="text" name="escritorio_origem" value="NPJ-UNIVAG" maxlength="15"
                            class="form-control" id="id_escritorio_origem">
                    </div>
                </div>

                <!-- Classe: formulário inline (um baixo do outro) -->
                <div class="form-group">
                    <label for="id_cliente">
                        <span class="required">Cliente no NPJ-UNIVAG</span>
                    </label>
                    <input type="text" name="cliente" maxlength="100" class="form-control" required="" id="id_cliente">
                    <div class="invalid-feedback">
                        Insira o nome completo do cliente.
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_contrario">
                        <span class="required">Contrário</span>
                    </label>
                    <input type="text" name="contrario" maxlength="100" class="form-control" required=""
                        id="id_contrario">
                    <div class="invalid-feedback">
                        Insira o nome completo.
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_tipo_action">
                        <span class="required">Tipo de ação</span>
                    </label>
                    <input type="text" name="tipo_action" maxlength="100" class="form-control" required=""
                        id="id_tipo_action">
                    <div class="invalid-feedback">
                        Por favor, forneça o tipo de ação.
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="id_n_principal">
                            Nº Principal
                        </label>
                        <input type="number" name="n_principal" min="0" class="form-control" id="id_n_principal"
                            placeholder="Apenas números.">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_orgao_principal">
                            Orgão
                        </label>
                        <input type="text" name="orgao_principal" maxlength="128" class="form-control"
                            id="id_orgao_principal">
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="id_professor">
                            Professor Orientador
                        </label>
                        <input type="text" name="professor" value="BRUNO HENRIQUE DA ROCHA" maxlength="100"
                            class="form-control" id="id_professor">
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="id_natureza">
                            <span class="required">Natureza</span>
                        </label>
                        <input type="text" name="natureza" maxlength="100" class="form-control" required=""
                            id="id_natureza">
                        <div class="invalid-feedback">
                            Por favor, forneça a natureza do processo.
                        </div>
                    </div>
                </div>

                <!-- Classe: Check list (quadrado para 'ok') -->
                <div style="margin-top:10px;" class="form-check">
                    <input type="checkbox" name="status" class="form-check-input" id="id_status">
                    <label class="form-check-label" for="id_status">Encerrado</label>
                </div>

                <!-- Classe: grupo de botões (Criado por mim)-->
                <div class="button_form">
                    <button style="margin-right: 10px;" type="submit" class="btn btn-success">
                        <span class="fa fa-check"></span>&nbsp;Cadastrar
                    </button>

                    <!-- Redireciona para a url caso for clicado -->
                    <a href="{% url 'description:processo_list' %}">
                        <button type="button" class="btn btn-primary">
                            <span class="fa fa-close"></span>&nbsp;Cancelar
                        </button>
                    </a>
                </div>
            </form>
        </div>
    </div>

    <!-- Configurações de JS para a classe 'invalid-feedback' funcionar -->
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>

    {% endblock content %}

</body>

</html>