processos/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/$', views.list_event, name='list_event'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/new/(?P<id_cliente>\d+)/$', views.event, name='event_new'),
]

processos/core/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'core'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('cadastrar_usuario/',views.cadastrar_user, name="cadastrar_user"),
    path('deslogar_usuario/', views.deslogar_user, name="deslogar_user"),
    path('alterar_senha/', views.alterar_senha, name="alterar_senha"),
    path('', views.logar_user, name="logar_user"),
]

processos/descricao/urls.py
from django.urls import path
from . import views

# Nome do aplicativo
app_name = 'description'

# Urls, 'nome', views.definição_do_Que_vai_ser_visto, name='nome_para_chamar_url'
urlpatterns = [
    path('', views.processo_list, name='processo_list'),
    path('<int:pk>/', views.processo_detail, name='processo_detail'),
    path('add/', views.ProcessoCreate.as_view(), name='processo_add'),
    path('deletar/<int:id>/', views.processo_delete, name='processo_delete'),
]

processos/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('processos.core.urls')),
    path('processos/', include('processos.descricao.urls')),
    path('comentario/', include('processos.comment.urls')),
     path('calendario/', include('processos.cal.urls')),
]

processos/core/models.py
from django.db import models

class TimeStampedModel(models.Model):
    """Cria uma tabela que contém as informações de criação do produto e sua modificação"""
    created = models.DateTimeField('criado em', auto_now=False, auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True

processos/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import  AuthenticationForm, UserCreationForm, PasswordChangeForm


@login_required(login_url='core:logar_user')
def index(request):
    template_name = 'index.html'
    return render(request,template_name)


def logar_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('core:index')
        else:
            form_login = AuthenticationForm()
    else:
        form_login = AuthenticationForm()
    return render(request, 'login.html', {'form_login': form_login})


def cadastrar_user(request):
    if request.method == 'POST':
        form_user = UserCreationForm(request.POST)
        if form_user.is_valid():
            form_user.save()
            return redirect('core:index')

    else:
        form_user = UserCreationForm()

    context = {'form_user': form_user}
    return render(request, 'cadastro.html', context)


@login_required(login_url='core:logar_user')
def deslogar_user(request):
    logout(request)
    return redirect('core:logar_user')


@login_required(login_url='core:logar_user')
def alterar_senha(request):
    if request.method == "POST":
        form_senha = PasswordChangeForm(request.user, request.POST)
        if form_senha.is_valid():
            user = form_senha.save()
            update_session_auth_hash(request, user)
            return redirect('core:index')
    else:
        form_senha = PasswordChangeForm(request.user)
    return render(request, 'alterar_senha.html', {'form_senha': form_senha})

processos/core/templates/includes/nav.html
<!--https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html-->
<!--Criação de um menu-->

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <style>

    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand">Registro</a> <!-- Define o nome do menu -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <!-- Nome e links do menu-->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'description:processo_list' %}">Processos</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Agenda
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'cal:calendar' %}">Calendário</a>
                        <a class="dropdown-item" href="{% url 'cal:list_event' %}">Eventos</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:deslogar_user' %}">Sair</a>
                </li>
            </ul>
            <!-- Sistema de busca no menu
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->
        </div>
    </nav>
</body>

</html>